// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.1.84
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BuildingBlocks.Membership.RavenDB.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.1.84")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("хранилище учетных записей пользователей")]
    public partial class ХранилищеУчетныхЗаписейПользователейFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UserRepository.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "хранилище учетных записей пользователей", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя",
                        "email"});
            table1.AddRow(new string[] {
                        "Сидоров",
                        "Сидоров@outlook.com"});
            table1.AddRow(new string[] {
                        "Петров",
                        "Петров@mail.ru"});
            table1.AddRow(new string[] {
                        "Иванов",
                        "Иванов@gmail.com"});
#line 5
testRunner.Given("существуют пользователи", ((string)(null)), table1, "Пусть ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка отсортированных по имени пользователей пользователей соотве" +
            "тствующих части email")]
        public virtual void ПостраничнаяЗагрузкаОтсортированныхПоИмениПользователейПользователейСоответствующихЧастиEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка отсортированных по имени пользователей пользователей соотве" +
                    "тствующих части email", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя",
                        "email"});
            table2.AddRow(new string[] {
                        "Медведев",
                        "Сидоров@kreml.uc"});
            table2.AddRow(new string[] {
                        "Медведева",
                        "Петров@kreml.uc"});
            table2.AddRow(new string[] {
                        "Путин",
                        "Путин@kreml.uc"});
            table2.AddRow(new string[] {
                        "Кабаева",
                        "Кабаева@kreml.uc"});
            table2.AddRow(new string[] {
                        "Сабчак",
                        "Сабчак@mail.ru"});
#line 12
 testRunner.Given("существуют пользователи", ((string)(null)), table2, "Пусть ");
#line 19
 testRunner.When("загружают 1 страницу пользоватлей по 3 пользователя с фильтром по email \"kreml.uc" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table3.AddRow(new string[] {
                        "Кабаева"});
            table3.AddRow(new string[] {
                        "Медведев"});
            table3.AddRow(new string[] {
                        "Медведева"});
#line 20
 testRunner.Then("возвращается страница с пользователями", ((string)(null)), table3, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка пользователей соответствующих части имени")]
        [NUnit.Framework.TestCaseAttribute("едве", "4", "3", null)]
        [NUnit.Framework.TestCaseAttribute("", "8", "3", null)]
        public virtual void ПостраничнаяЗагрузкаПользователейСоответствующихЧастиИмени(string фильтр, string всего, string наСтранице, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка пользователей соответствующих части имени", exampleTags);
#line 26
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table4.AddRow(new string[] {
                        "Медведев"});
            table4.AddRow(new string[] {
                        "Медведева"});
            table4.AddRow(new string[] {
                        "Медвед"});
            table4.AddRow(new string[] {
                        "Медведица"});
            table4.AddRow(new string[] {
                        "Сабчак"});
#line 27
 testRunner.Given("существуют пользователи", ((string)(null)), table4, "Пусть ");
#line 34
 testRunner.When(string.Format("загружают 1 страницу пользоватлей по 3 пользователя с фильтром по имени \"{0}\"", фильтр), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "всего",
                        "на странице"});
            table5.AddRow(new string[] {
                        string.Format("{0}", всего),
                        string.Format("{0}", наСтранице)});
#line 35
 testRunner.Then("возвращается страница пользователей", ((string)(null)), table5, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка пользователей соответствующих приложению и части имени")]
        [NUnit.Framework.TestCaseAttribute("едве", "Ru", "4", "3", null)]
        [NUnit.Framework.TestCaseAttribute("едве", "Yandex", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("", "Ru", "4", "3", null)]
        [NUnit.Framework.TestCaseAttribute("", "Yandex", "1", "1", null)]
        public virtual void ПостраничнаяЗагрузкаПользователейСоответствующихПриложениюИЧастиИмени(string фильтр, string приложение, string всего, string наСтранице, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка пользователей соответствующих приложению и части имени", exampleTags);
#line 43
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя",
                        "приложение"});
            table6.AddRow(new string[] {
                        "Медведев",
                        "Ru"});
            table6.AddRow(new string[] {
                        "Медведева",
                        "Ru"});
            table6.AddRow(new string[] {
                        "Медвед",
                        "Ru"});
            table6.AddRow(new string[] {
                        "Медведица",
                        "Ru"});
            table6.AddRow(new string[] {
                        "Сабчак",
                        "Yandex"});
#line 44
 testRunner.Given("существуют пользователи", ((string)(null)), table6, "Пусть ");
#line 51
 testRunner.When(string.Format("загружают 1 страницу пользоватлей по 3 пользователя, по приложению \"{0}\" и части " +
                        "имени \"{1}\"", приложение, фильтр), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "всего",
                        "на странице"});
            table7.AddRow(new string[] {
                        string.Format("{0}", всего),
                        string.Format("{0}", наСтранице)});
#line 52
 testRunner.Then("возвращается страница пользователей", ((string)(null)), table7, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка отсортированных по имени пользователей соответствующих част" +
            "и имени")]
        public virtual void ПостраничнаяЗагрузкаОтсортированныхПоИмениПользователейСоответствующихЧастиИмени()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка отсортированных по имени пользователей соответствующих част" +
                    "и имени", ((string[])(null)));
#line 62
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table8.AddRow(new string[] {
                        "Медведев"});
            table8.AddRow(new string[] {
                        "Медведева"});
            table8.AddRow(new string[] {
                        "Медвед"});
            table8.AddRow(new string[] {
                        "Медведица"});
            table8.AddRow(new string[] {
                        "Сабчак"});
#line 63
 testRunner.Given("существуют пользователи", ((string)(null)), table8, "Пусть ");
#line 70
 testRunner.When("загружают 1 страницу пользоватлей по 3 пользователя с фильтром по имени \"едве\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table9.AddRow(new string[] {
                        "Медвед"});
            table9.AddRow(new string[] {
                        "Медведев"});
            table9.AddRow(new string[] {
                        "Медведева"});
#line 71
 testRunner.Then("возвращается страница с пользователями", ((string)(null)), table9, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка пользователей")]
        public virtual void ПостраничнаяЗагрузкаПользователей()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка пользователей", ((string[])(null)));
#line 77
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table10.AddRow(new string[] {
                        "Медведев"});
            table10.AddRow(new string[] {
                        "Медведева"});
            table10.AddRow(new string[] {
                        "Медвед"});
            table10.AddRow(new string[] {
                        "Медведица"});
            table10.AddRow(new string[] {
                        "Сабчак"});
#line 78
 testRunner.Given("существуют пользователи", ((string)(null)), table10, "Пусть ");
#line 85
 testRunner.When("загружают 1 страницу пользоватлей по 3 пользователя", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "всего",
                        "на странице"});
            table11.AddRow(new string[] {
                        "8",
                        "3"});
#line 86
 testRunner.Then("возвращается страница пользователей", ((string)(null)), table11, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка отсортированных по имени пользователей")]
        public virtual void ПостраничнаяЗагрузкаОтсортированныхПоИмениПользователей()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка отсортированных по имени пользователей", ((string[])(null)));
#line 90
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table12.AddRow(new string[] {
                        "Медведев"});
            table12.AddRow(new string[] {
                        "Медведева"});
            table12.AddRow(new string[] {
                        "Путин"});
            table12.AddRow(new string[] {
                        "Кабаева"});
            table12.AddRow(new string[] {
                        "Сабчак"});
#line 91
 testRunner.Given("существуют пользователи", ((string)(null)), table12, "Пусть ");
#line 98
 testRunner.When("загружают 1 страницу пользоватлей по 3 пользователя", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table13.AddRow(new string[] {
                        "Иванов"});
            table13.AddRow(new string[] {
                        "Кабаева"});
            table13.AddRow(new string[] {
                        "Медведев"});
#line 99
 testRunner.Then("возвращается страница с пользователями", ((string)(null)), table13, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("количество пользователей с последней активностью не меньше указанной даты")]
        public virtual void КоличествоПользователейСПоследнейАктивностьюНеМеньшеУказаннойДаты()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("количество пользователей с последней активностью не меньше указанной даты", ((string[])(null)));
#line 105
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя",
                        "активность"});
            table14.AddRow(new string[] {
                        "Сидоров",
                        "12.02.2012"});
            table14.AddRow(new string[] {
                        "Иванов",
                        "30.10.2012"});
            table14.AddRow(new string[] {
                        "Петров",
                        "29.10.2012"});
#line 106
 testRunner.Given("задана активность пользователей", ((string)(null)), table14, "Пусть ");
#line 111
 testRunner.When("получают количество пользователей с последней активностью от 28.10.2012", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 112
 testRunner.Then("количество пользователей равно 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("создание пользователя с пустым списком ролей")]
        public virtual void СозданиеПользователяСПустымСпискомРолей()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("создание пользователя с пустым списком ролей", ((string[])(null)));
#line 114
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table15.AddRow(new string[] {
                        "Врач"});
            table15.AddRow(new string[] {
                        "Медсестра"});
            table15.AddRow(new string[] {
                        "Админ"});
#line 115
 testRunner.Given("существуют роли", ((string)(null)), table15, "Пусть ");
#line 120
 testRunner.When("создают нового пользователя \"Медведев\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 121
 testRunner.Then("существует 4 пользователя", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
#line 122
 testRunner.And("существует пользователь \"Медведев\" со списком ролей", ((string)(null)), table16, "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("создание пользователя со списом ролей")]
        public virtual void СозданиеПользователяСоСписомРолей()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("создание пользователя со списом ролей", ((string[])(null)));
#line 125
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table17.AddRow(new string[] {
                        "Врач"});
            table17.AddRow(new string[] {
                        "Медсестра"});
            table17.AddRow(new string[] {
                        "Админ"});
#line 126
 testRunner.Given("существуют роли", ((string)(null)), table17, "Пусть ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table18.AddRow(new string[] {
                        "Медсестра"});
            table18.AddRow(new string[] {
                        "Админ"});
#line 131
 testRunner.When("создают нового пользователя \"Медведев\" с назначенными ролями", ((string)(null)), table18, "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table19.AddRow(new string[] {
                        "Медведев"});
#line 135
 testRunner.Then("существует роль \"Админ\" со списком пользователей", ((string)(null)), table19, "Тогда ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table20.AddRow(new string[] {
                        "Медведев"});
#line 138
 testRunner.And("существует роль \"Медсестра\" со списком пользователей", ((string)(null)), table20, "И ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table21.AddRow(new string[] {
                        "Медсестра"});
            table21.AddRow(new string[] {
                        "Админ"});
#line 141
 testRunner.And("существует пользователь \"Медведев\" со списком ролей", ((string)(null)), table21, "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("обновление пользователя")]
        public virtual void ОбновлениеПользователя()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("обновление пользователя", ((string[])(null)));
#line 146
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table22.AddRow(new string[] {
                        "Медведев"});
#line 147
 testRunner.Given("существуют пользователи", ((string)(null)), table22, "Пусть ");
#line 150
 testRunner.Given("пользователь \"Медведев\" имеет Id \"C6AFF080-2B78-453A-B841-F37E91B36483\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Пусть ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "поле",
                        "значение"});
            table23.AddRow(new string[] {
                        "Email",
                        "Медведев@mail.ru"});
            table23.AddRow(new string[] {
                        "ApplicationName",
                        "Unknown"});
            table23.AddRow(new string[] {
                        "Имя",
                        "Медвед"});
            table23.AddRow(new string[] {
                        "Пароль",
                        "7F664E0F-177E-4582-B057-23546388052D"});
            table23.AddRow(new string[] {
                        "Комментарий",
                        "Бла бла"});
            table23.AddRow(new string[] {
                        "ConfirmationToken",
                        "123a"});
            table23.AddRow(new string[] {
                        "CreateDate",
                        "12.02.2012"});
            table23.AddRow(new string[] {
                        "IsApproved",
                        "true"});
            table23.AddRow(new string[] {
                        "IsLockedOut",
                        "false"});
            table23.AddRow(new string[] {
                        "LastActivityDate",
                        "25.10.2012"});
            table23.AddRow(new string[] {
                        "LastLockoutDate",
                        "12.06.2012"});
            table23.AddRow(new string[] {
                        "LastLoginDate",
                        "25.10.2012"});
            table23.AddRow(new string[] {
                        "LastPasswordChangedDate",
                        "13.06.2012"});
            table23.AddRow(new string[] {
                        "LastPasswordFailureDate",
                        "11.06.2012"});
            table23.AddRow(new string[] {
                        "PasswordFailuresSinceLastSuccess",
                        "2"});
            table23.AddRow(new string[] {
                        "PasswordVerificationToken",
                        "456a"});
            table23.AddRow(new string[] {
                        "PasswordVerificationTokenExpirationDate",
                        "26.10.2012"});
#line 151
 testRunner.When("для пользователя с Id \"C6AFF080-2B78-453A-B841-F37E91B36483\" обновляют поля", ((string)(null)), table23, "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "поле",
                        "значение"});
            table24.AddRow(new string[] {
                        "Email",
                        "Медведев@mail.ru"});
            table24.AddRow(new string[] {
                        "Имя",
                        "Медвед"});
            table24.AddRow(new string[] {
                        "ApplicationName",
                        "Unknown"});
            table24.AddRow(new string[] {
                        "Пароль",
                        "7F664E0F-177E-4582-B057-23546388052D"});
            table24.AddRow(new string[] {
                        "Комментарий",
                        "Бла бла"});
            table24.AddRow(new string[] {
                        "ConfirmationToken",
                        "123a"});
            table24.AddRow(new string[] {
                        "CreateDate",
                        "12.02.2012"});
            table24.AddRow(new string[] {
                        "IsApproved",
                        "true"});
            table24.AddRow(new string[] {
                        "IsLockedOut",
                        "false"});
            table24.AddRow(new string[] {
                        "LastActivityDate",
                        "25.10.2012"});
            table24.AddRow(new string[] {
                        "LastLockoutDate",
                        "12.06.2012"});
            table24.AddRow(new string[] {
                        "LastLoginDate",
                        "25.10.2012"});
            table24.AddRow(new string[] {
                        "LastPasswordChangedDate",
                        "13.06.2012"});
            table24.AddRow(new string[] {
                        "LastPasswordFailureDate",
                        "11.06.2012"});
            table24.AddRow(new string[] {
                        "PasswordFailuresSinceLastSuccess",
                        "2"});
            table24.AddRow(new string[] {
                        "PasswordVerificationToken",
                        "456a"});
            table24.AddRow(new string[] {
                        "PasswordVerificationTokenExpirationDate",
                        "26.10.2012"});
#line 170
 testRunner.Then("пользователь с Id \"C6AFF080-2B78-453A-B841-F37E91B36483\" имеет следующие поля", ((string)(null)), table24, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("обновление ролей пользователя")]
        public virtual void ОбновлениеРолейПользователя()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("обновление ролей пользователя", ((string[])(null)));
#line 190
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table25.AddRow(new string[] {
                        "Врач"});
            table25.AddRow(new string[] {
                        "Медсестра"});
            table25.AddRow(new string[] {
                        "Админ"});
#line 191
 testRunner.Given("существуют роли", ((string)(null)), table25, "Пусть ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table26.AddRow(new string[] {
                        "Медсестра"});
            table26.AddRow(new string[] {
                        "Админ"});
#line 196
 testRunner.When("создают нового пользователя \"Медведев\" с назначенными ролями", ((string)(null)), table26, "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table27.AddRow(new string[] {
                        "Админ"});
            table27.AddRow(new string[] {
                        "Врач"});
#line 200
 testRunner.When("пользователю \"Медведев\" меняют назначение ролей", ((string)(null)), table27, "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table28.AddRow(new string[] {
                        "Админ"});
            table28.AddRow(new string[] {
                        "Врач"});
#line 204
 testRunner.Then("существует пользователь \"Медведев\" со списком ролей", ((string)(null)), table28, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удаление пользователя")]
        public virtual void УдалениеПользователя()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удаление пользователя", ((string[])(null)));
#line 209
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table29.AddRow(new string[] {
                        "Врач"});
            table29.AddRow(new string[] {
                        "Медсестра"});
            table29.AddRow(new string[] {
                        "Админ"});
#line 210
 testRunner.Given("существуют роли", ((string)(null)), table29, "Пусть ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table30.AddRow(new string[] {
                        "Медсестра"});
            table30.AddRow(new string[] {
                        "Админ"});
#line 215
 testRunner.When("создают нового пользователя \"Медведев\" с назначенными ролями", ((string)(null)), table30, "Когда ");
#line 219
 testRunner.And("удаляют пользователя \"Медведев\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 220
 testRunner.Then("существует 3 пользователя", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
