// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.1.84
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BuildingBlocks.Membership.RavenDB.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.1.84")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("хранилище учетных записей пользователей")]
    public partial class ХранилищеУчетныхЗаписейПользователейFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UserRepository.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "хранилище учетных записей пользователей", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя",
                        "email"});
            table1.AddRow(new string[] {
                        "Сидоров",
                        "Сидоров@outlook.com"});
            table1.AddRow(new string[] {
                        "Петров",
                        "Петров@mail.ru"});
            table1.AddRow(new string[] {
                        "Иванов",
                        "Иванов@gmail.com"});
#line 5
testRunner.Given("существуют пользователи", ((string)(null)), table1, "Пусть ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("проверка существования пользователя по имени")]
        [NUnit.Framework.TestCaseAttribute("Иванов", "существует", null)]
        [NUnit.Framework.TestCaseAttribute("Петров", "существует", null)]
        [NUnit.Framework.TestCaseAttribute("Сидоров", "существует", null)]
        [NUnit.Framework.TestCaseAttribute("Медведев", "не существует", null)]
        public virtual void ПроверкаСуществованияПользователяПоИмени(string имя, string существует, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("проверка существования пользователя по имени", exampleTags);
#line 11
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 12
 testRunner.When(string.Format("проверяют что пользователь с именем \"{0}\" существует", имя), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 13
 testRunner.Then(string.Format("результат проверки признает что пользователь \"{0}\"", существует), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("проверка существования пользователя по email")]
        [NUnit.Framework.TestCaseAttribute("Иванов@gmail.com", "существует", null)]
        [NUnit.Framework.TestCaseAttribute("Петров@mail.ru", "существует", null)]
        [NUnit.Framework.TestCaseAttribute("Сидоров@outlook.com", "существует", null)]
        [NUnit.Framework.TestCaseAttribute("Иванов@mail.ru", "не существует", null)]
        public virtual void ПроверкаСуществованияПользователяПоEmail(string email, string существует, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("проверка существования пользователя по email", exampleTags);
#line 21
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 22
 testRunner.When(string.Format("проверяют что пользователь с email \"{0}\" существует", email), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 23
 testRunner.Then(string.Format("результат проверки признает что пользователь \"{0}\"", существует), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("поиск пользователей по списку имен")]
        public virtual void ПоискПользователейПоСпискуИмен()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("поиск пользователей по списку имен", ((string[])(null)));
#line 31
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table2.AddRow(new string[] {
                        "Путин"});
            table2.AddRow(new string[] {
                        "Иванов"});
            table2.AddRow(new string[] {
                        "Петров"});
#line 32
 testRunner.When("получают список пользователей содержащих имена", ((string)(null)), table2, "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table3.AddRow(new string[] {
                        "Иванов"});
            table3.AddRow(new string[] {
                        "Петров"});
#line 37
 testRunner.Then("возвращается следующий список пользователей", ((string)(null)), table3, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("поиск пользователя по email")]
        public virtual void ПоискПользователяПоEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("поиск пользователя по email", ((string[])(null)));
#line 42
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 43
 testRunner.When("ищут пользователя с email \"Сидоров@outlook.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table4.AddRow(new string[] {
                        "Сидоров"});
#line 44
 testRunner.Then("возвращается следующий список пользователей", ((string)(null)), table4, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("поиск пользователя по не существующему email")]
        public virtual void ПоискПользователяПоНеСуществующемуEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("поиск пользователя по не существующему email", ((string[])(null)));
#line 48
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 49
 testRunner.When("ищут пользователя с email \"Сидоров@outlook.net\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 50
 testRunner.Then("не возвращается ни одного пользователя", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("поиск пользователя по Id")]
        public virtual void ПоискПользователяПоId()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("поиск пользователя по Id", ((string[])(null)));
#line 52
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 53
 testRunner.Given("пользователь \"Сидоров\" имеет Id \"94BB18FA-5198-4445-88A0-4475A7A715FC\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Пусть ");
#line 54
 testRunner.When("ищут пользователя с Id \"94BB18FA-5198-4445-88A0-4475A7A715FC\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table5.AddRow(new string[] {
                        "Сидоров"});
#line 55
 testRunner.Then("возвращается следующий список пользователей", ((string)(null)), table5, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("поиск пользователя по не существующему Id")]
        public virtual void ПоискПользователяПоНеСуществующемуId()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("поиск пользователя по не существующему Id", ((string[])(null)));
#line 59
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 60
 testRunner.Given("пользователь \"Сидоров\" имеет Id \"94BB18FA-5198-4445-88A0-4475A7A715FC\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Пусть ");
#line 61
 testRunner.When("ищут пользователя с Id \"6D4DA51A-FCF3-4343-B63D-E20468F90B0B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 62
 testRunner.Then("не возвращается ни одного пользователя", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка пользователей соответствующих части email")]
        [NUnit.Framework.TestCaseAttribute("kreml.uc", "4", "3", null)]
        [NUnit.Framework.TestCaseAttribute("", "8", "3", null)]
        public virtual void ПостраничнаяЗагрузкаПользователейСоответствующихЧастиEmail(string фильтр, string всего, string наСтранице, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка пользователей соответствующих части email", exampleTags);
#line 64
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя",
                        "email"});
            table6.AddRow(new string[] {
                        "Медведев",
                        "Сидоров@kreml.uc"});
            table6.AddRow(new string[] {
                        "Медведева",
                        "Петров@kreml.uc"});
            table6.AddRow(new string[] {
                        "Путин",
                        "Путин@kreml.uc"});
            table6.AddRow(new string[] {
                        "Кабаева",
                        "Кабаева@kreml.uc"});
            table6.AddRow(new string[] {
                        "Сабчак",
                        "Сабчак@mail.ru"});
#line 65
 testRunner.Given("существуют пользователи", ((string)(null)), table6, "Пусть ");
#line 72
 testRunner.When(string.Format("загружают 1 страницу пользоватлей по 3 пользователя с фильтром по email \"{0}\"", фильтр), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "всего",
                        "на странице"});
            table7.AddRow(new string[] {
                        string.Format("{0}", всего),
                        string.Format("{0}", наСтранице)});
#line 73
 testRunner.Then("возвращается страница пользователей", ((string)(null)), table7, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка пользователей соответствующих части email и имени приложени" +
            "я")]
        [NUnit.Framework.TestCaseAttribute("kreml.uc", "Ru", "4", "3", null)]
        [NUnit.Framework.TestCaseAttribute("", "Ru", "5", "3", null)]
        [NUnit.Framework.TestCaseAttribute("", "Yandex", "1", "1", null)]
        [NUnit.Framework.TestCaseAttribute("kreml", "Yandex", "1", "1", null)]
        [NUnit.Framework.TestCaseAttribute("kreml.uc", "Yandex", "0", "0", null)]
        public virtual void ПостраничнаяЗагрузкаПользователейСоответствующихЧастиEmailИИмениПриложения(string фильтр, string приложение, string всего, string наСтранице, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка пользователей соответствующих части email и имени приложени" +
                    "я", exampleTags);
#line 81
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя",
                        "email",
                        "приложение"});
            table8.AddRow(new string[] {
                        "Медведев",
                        "Сидоров@kreml.uc",
                        "Ru"});
            table8.AddRow(new string[] {
                        "Медведева",
                        "Петров@kreml.uc",
                        "Ru"});
            table8.AddRow(new string[] {
                        "Путин",
                        "Путин@kreml.uc",
                        "Ru"});
            table8.AddRow(new string[] {
                        "Кабаева",
                        "Кабаева@kreml.uc",
                        "Ru"});
            table8.AddRow(new string[] {
                        "Кабаев",
                        "Кабаева@yanndex.uc",
                        "Ru"});
            table8.AddRow(new string[] {
                        "Сабчак",
                        "Сабчак@kreml.ru",
                        "Yandex"});
#line 82
 testRunner.Given("существуют пользователи", ((string)(null)), table8, "Пусть ");
#line 90
 testRunner.When(string.Format("загружают 1 страницу пользоватлей по 3 пользователя, по приложению \"{0}\" и части " +
                        "email \"{1}\"", приложение, фильтр), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "всего",
                        "на странице"});
            table9.AddRow(new string[] {
                        string.Format("{0}", всего),
                        string.Format("{0}", наСтранице)});
#line 91
 testRunner.Then("возвращается страница пользователей", ((string)(null)), table9, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка отсортированных по имени пользователей пользователей соотве" +
            "тствующих части email")]
        public virtual void ПостраничнаяЗагрузкаОтсортированныхПоИмениПользователейПользователейСоответствующихЧастиEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка отсортированных по имени пользователей пользователей соотве" +
                    "тствующих части email", ((string[])(null)));
#line 102
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя",
                        "email"});
            table10.AddRow(new string[] {
                        "Медведев",
                        "Сидоров@kreml.uc"});
            table10.AddRow(new string[] {
                        "Медведева",
                        "Петров@kreml.uc"});
            table10.AddRow(new string[] {
                        "Путин",
                        "Путин@kreml.uc"});
            table10.AddRow(new string[] {
                        "Кабаева",
                        "Кабаева@kreml.uc"});
            table10.AddRow(new string[] {
                        "Сабчак",
                        "Сабчак@mail.ru"});
#line 103
 testRunner.Given("существуют пользователи", ((string)(null)), table10, "Пусть ");
#line 110
 testRunner.When("загружают 1 страницу пользоватлей по 3 пользователя с фильтром по email \"kreml.uc" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table11.AddRow(new string[] {
                        "Кабаева"});
            table11.AddRow(new string[] {
                        "Медведев"});
            table11.AddRow(new string[] {
                        "Медведева"});
#line 111
 testRunner.Then("возвращается страница с пользователями", ((string)(null)), table11, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка пользователей соответствующих части имени")]
        [NUnit.Framework.TestCaseAttribute("едве", "4", "3", null)]
        [NUnit.Framework.TestCaseAttribute("", "8", "3", null)]
        public virtual void ПостраничнаяЗагрузкаПользователейСоответствующихЧастиИмени(string фильтр, string всего, string наСтранице, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка пользователей соответствующих части имени", exampleTags);
#line 117
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table12.AddRow(new string[] {
                        "Медведев"});
            table12.AddRow(new string[] {
                        "Медведева"});
            table12.AddRow(new string[] {
                        "Медвед"});
            table12.AddRow(new string[] {
                        "Медведица"});
            table12.AddRow(new string[] {
                        "Сабчак"});
#line 118
 testRunner.Given("существуют пользователи", ((string)(null)), table12, "Пусть ");
#line 125
 testRunner.When(string.Format("загружают 1 страницу пользоватлей по 3 пользователя с фильтром по имени \"{0}\"", фильтр), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "всего",
                        "на странице"});
            table13.AddRow(new string[] {
                        string.Format("{0}", всего),
                        string.Format("{0}", наСтранице)});
#line 126
 testRunner.Then("возвращается страница пользователей", ((string)(null)), table13, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка пользователей соответствующих приложению и части имени")]
        [NUnit.Framework.TestCaseAttribute("едве", "Ru", "4", "3", null)]
        [NUnit.Framework.TestCaseAttribute("едве", "Yandex", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("", "Ru", "4", "3", null)]
        [NUnit.Framework.TestCaseAttribute("", "Yandex", "1", "1", null)]
        public virtual void ПостраничнаяЗагрузкаПользователейСоответствующихПриложениюИЧастиИмени(string фильтр, string приложение, string всего, string наСтранице, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка пользователей соответствующих приложению и части имени", exampleTags);
#line 134
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя",
                        "приложение"});
            table14.AddRow(new string[] {
                        "Медведев",
                        "Ru"});
            table14.AddRow(new string[] {
                        "Медведева",
                        "Ru"});
            table14.AddRow(new string[] {
                        "Медвед",
                        "Ru"});
            table14.AddRow(new string[] {
                        "Медведица",
                        "Ru"});
            table14.AddRow(new string[] {
                        "Сабчак",
                        "Yandex"});
#line 135
 testRunner.Given("существуют пользователи", ((string)(null)), table14, "Пусть ");
#line 142
 testRunner.When(string.Format("загружают 1 страницу пользоватлей по 3 пользователя, по приложению \"{0}\" и части " +
                        "имени \"{1}\"", приложение, фильтр), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "всего",
                        "на странице"});
            table15.AddRow(new string[] {
                        string.Format("{0}", всего),
                        string.Format("{0}", наСтранице)});
#line 143
 testRunner.Then("возвращается страница пользователей", ((string)(null)), table15, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка отсортированных по имени пользователей соответствующих част" +
            "и имени")]
        public virtual void ПостраничнаяЗагрузкаОтсортированныхПоИмениПользователейСоответствующихЧастиИмени()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка отсортированных по имени пользователей соответствующих част" +
                    "и имени", ((string[])(null)));
#line 153
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table16.AddRow(new string[] {
                        "Медведев"});
            table16.AddRow(new string[] {
                        "Медведева"});
            table16.AddRow(new string[] {
                        "Медвед"});
            table16.AddRow(new string[] {
                        "Медведица"});
            table16.AddRow(new string[] {
                        "Сабчак"});
#line 154
 testRunner.Given("существуют пользователи", ((string)(null)), table16, "Пусть ");
#line 161
 testRunner.When("загружают 1 страницу пользоватлей по 3 пользователя с фильтром по имени \"едве\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table17.AddRow(new string[] {
                        "Медвед"});
            table17.AddRow(new string[] {
                        "Медведев"});
            table17.AddRow(new string[] {
                        "Медведева"});
#line 162
 testRunner.Then("возвращается страница с пользователями", ((string)(null)), table17, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка пользователей")]
        public virtual void ПостраничнаяЗагрузкаПользователей()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка пользователей", ((string[])(null)));
#line 168
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table18.AddRow(new string[] {
                        "Медведев"});
            table18.AddRow(new string[] {
                        "Медведева"});
            table18.AddRow(new string[] {
                        "Медвед"});
            table18.AddRow(new string[] {
                        "Медведица"});
            table18.AddRow(new string[] {
                        "Сабчак"});
#line 169
 testRunner.Given("существуют пользователи", ((string)(null)), table18, "Пусть ");
#line 176
 testRunner.When("загружают 1 страницу пользоватлей по 3 пользователя", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "всего",
                        "на странице"});
            table19.AddRow(new string[] {
                        "8",
                        "3"});
#line 177
 testRunner.Then("возвращается страница пользователей", ((string)(null)), table19, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("постраничная загрузка отсортированных по имени пользователей")]
        public virtual void ПостраничнаяЗагрузкаОтсортированныхПоИмениПользователей()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("постраничная загрузка отсортированных по имени пользователей", ((string[])(null)));
#line 181
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table20.AddRow(new string[] {
                        "Медведев"});
            table20.AddRow(new string[] {
                        "Медведева"});
            table20.AddRow(new string[] {
                        "Путин"});
            table20.AddRow(new string[] {
                        "Кабаева"});
            table20.AddRow(new string[] {
                        "Сабчак"});
#line 182
 testRunner.Given("существуют пользователи", ((string)(null)), table20, "Пусть ");
#line 189
 testRunner.When("загружают 1 страницу пользоватлей по 3 пользователя", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table21.AddRow(new string[] {
                        "Иванов"});
            table21.AddRow(new string[] {
                        "Кабаева"});
            table21.AddRow(new string[] {
                        "Медведев"});
#line 190
 testRunner.Then("возвращается страница с пользователями", ((string)(null)), table21, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("количество пользователей с последней активностью не меньше указанной даты")]
        public virtual void КоличествоПользователейСПоследнейАктивностьюНеМеньшеУказаннойДаты()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("количество пользователей с последней активностью не меньше указанной даты", ((string[])(null)));
#line 196
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя",
                        "активность"});
            table22.AddRow(new string[] {
                        "Сидоров",
                        "12.02.2012"});
            table22.AddRow(new string[] {
                        "Иванов",
                        "30.10.2012"});
            table22.AddRow(new string[] {
                        "Петров",
                        "29.10.2012"});
#line 197
 testRunner.Given("задана активность пользователей", ((string)(null)), table22, "Пусть ");
#line 202
 testRunner.When("получают количество пользователей с последней активностью от 28.10.2012", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 203
 testRunner.Then("количество пользователей равно 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("создание пользователя с пустым списком ролей")]
        public virtual void СозданиеПользователяСПустымСпискомРолей()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("создание пользователя с пустым списком ролей", ((string[])(null)));
#line 205
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table23.AddRow(new string[] {
                        "Врач"});
            table23.AddRow(new string[] {
                        "Медсестра"});
            table23.AddRow(new string[] {
                        "Админ"});
#line 206
 testRunner.Given("существуют роли", ((string)(null)), table23, "Пусть ");
#line 211
 testRunner.When("создают нового пользователя \"Медведев\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 212
 testRunner.Then("существует 4 пользователя", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
#line 213
 testRunner.And("существует пользователь \"Медведев\" со списком ролей", ((string)(null)), table24, "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("создание пользователя со списом ролей")]
        public virtual void СозданиеПользователяСоСписомРолей()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("создание пользователя со списом ролей", ((string[])(null)));
#line 216
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table25.AddRow(new string[] {
                        "Врач"});
            table25.AddRow(new string[] {
                        "Медсестра"});
            table25.AddRow(new string[] {
                        "Админ"});
#line 217
 testRunner.Given("существуют роли", ((string)(null)), table25, "Пусть ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table26.AddRow(new string[] {
                        "Медсестра"});
            table26.AddRow(new string[] {
                        "Админ"});
#line 222
 testRunner.When("создают нового пользователя \"Медведев\" с назначенными ролями", ((string)(null)), table26, "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table27.AddRow(new string[] {
                        "Медведев"});
#line 226
 testRunner.Then("существует роль \"Админ\" со списком пользователей", ((string)(null)), table27, "Тогда ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table28.AddRow(new string[] {
                        "Медведев"});
#line 229
 testRunner.And("существует роль \"Медсестра\" со списком пользователей", ((string)(null)), table28, "И ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table29.AddRow(new string[] {
                        "Медсестра"});
            table29.AddRow(new string[] {
                        "Админ"});
#line 232
 testRunner.And("существует пользователь \"Медведев\" со списком ролей", ((string)(null)), table29, "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("обновление пользователя")]
        public virtual void ОбновлениеПользователя()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("обновление пользователя", ((string[])(null)));
#line 237
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table30.AddRow(new string[] {
                        "Медведев"});
#line 238
 testRunner.Given("существуют пользователи", ((string)(null)), table30, "Пусть ");
#line 241
 testRunner.Given("пользователь \"Медведев\" имеет Id \"C6AFF080-2B78-453A-B841-F37E91B36483\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Пусть ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "поле",
                        "значение"});
            table31.AddRow(new string[] {
                        "Email",
                        "Медведев@mail.ru"});
            table31.AddRow(new string[] {
                        "ApplicationName",
                        "Unknown"});
            table31.AddRow(new string[] {
                        "Имя",
                        "Медвед"});
            table31.AddRow(new string[] {
                        "Пароль",
                        "7F664E0F-177E-4582-B057-23546388052D"});
            table31.AddRow(new string[] {
                        "Комментарий",
                        "Бла бла"});
            table31.AddRow(new string[] {
                        "ConfirmationToken",
                        "123a"});
            table31.AddRow(new string[] {
                        "CreateDate",
                        "12.02.2012"});
            table31.AddRow(new string[] {
                        "IsApproved",
                        "true"});
            table31.AddRow(new string[] {
                        "IsLockedOut",
                        "false"});
            table31.AddRow(new string[] {
                        "LastActivityDate",
                        "25.10.2012"});
            table31.AddRow(new string[] {
                        "LastLockoutDate",
                        "12.06.2012"});
            table31.AddRow(new string[] {
                        "LastLoginDate",
                        "25.10.2012"});
            table31.AddRow(new string[] {
                        "LastPasswordChangedDate",
                        "13.06.2012"});
            table31.AddRow(new string[] {
                        "LastPasswordFailureDate",
                        "11.06.2012"});
            table31.AddRow(new string[] {
                        "PasswordFailuresSinceLastSuccess",
                        "2"});
            table31.AddRow(new string[] {
                        "PasswordVerificationToken",
                        "456a"});
            table31.AddRow(new string[] {
                        "PasswordVerificationTokenExpirationDate",
                        "26.10.2012"});
#line 242
 testRunner.When("для пользователя с Id \"C6AFF080-2B78-453A-B841-F37E91B36483\" обновляют поля", ((string)(null)), table31, "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "поле",
                        "значение"});
            table32.AddRow(new string[] {
                        "Email",
                        "Медведев@mail.ru"});
            table32.AddRow(new string[] {
                        "Имя",
                        "Медвед"});
            table32.AddRow(new string[] {
                        "ApplicationName",
                        "Unknown"});
            table32.AddRow(new string[] {
                        "Пароль",
                        "7F664E0F-177E-4582-B057-23546388052D"});
            table32.AddRow(new string[] {
                        "Комментарий",
                        "Бла бла"});
            table32.AddRow(new string[] {
                        "ConfirmationToken",
                        "123a"});
            table32.AddRow(new string[] {
                        "CreateDate",
                        "12.02.2012"});
            table32.AddRow(new string[] {
                        "IsApproved",
                        "true"});
            table32.AddRow(new string[] {
                        "IsLockedOut",
                        "false"});
            table32.AddRow(new string[] {
                        "LastActivityDate",
                        "25.10.2012"});
            table32.AddRow(new string[] {
                        "LastLockoutDate",
                        "12.06.2012"});
            table32.AddRow(new string[] {
                        "LastLoginDate",
                        "25.10.2012"});
            table32.AddRow(new string[] {
                        "LastPasswordChangedDate",
                        "13.06.2012"});
            table32.AddRow(new string[] {
                        "LastPasswordFailureDate",
                        "11.06.2012"});
            table32.AddRow(new string[] {
                        "PasswordFailuresSinceLastSuccess",
                        "2"});
            table32.AddRow(new string[] {
                        "PasswordVerificationToken",
                        "456a"});
            table32.AddRow(new string[] {
                        "PasswordVerificationTokenExpirationDate",
                        "26.10.2012"});
#line 261
 testRunner.Then("пользователь с Id \"C6AFF080-2B78-453A-B841-F37E91B36483\" имеет следующие поля", ((string)(null)), table32, "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("обновление ролей пользователя")]
        public virtual void ОбновлениеРолейПользователя()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("обновление ролей пользователя", ((string[])(null)));
#line 281
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table33.AddRow(new string[] {
                        "Врач"});
            table33.AddRow(new string[] {
                        "Медсестра"});
            table33.AddRow(new string[] {
                        "Админ"});
#line 282
 testRunner.Given("существуют роли", ((string)(null)), table33, "Пусть ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table34.AddRow(new string[] {
                        "Медсестра"});
            table34.AddRow(new string[] {
                        "Админ"});
#line 287
 testRunner.When("создают нового пользователя \"Медведев\" с назначенными ролями", ((string)(null)), table34, "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table35.AddRow(new string[] {
                        "Админ"});
            table35.AddRow(new string[] {
                        "Врач"});
#line 291
 testRunner.When("пользователю \"Медведев\" меняют назначение ролей", ((string)(null)), table35, "Когда ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table36.AddRow(new string[] {
                        "Медведев"});
#line 295
 testRunner.Then("существует роль \"Админ\" со списком пользователей", ((string)(null)), table36, "Тогда ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table37.AddRow(new string[] {
                        "Админ"});
            table37.AddRow(new string[] {
                        "Врач"});
#line 298
 testRunner.And("существует пользователь \"Медведев\" со списком ролей", ((string)(null)), table37, "И ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table38.AddRow(new string[] {
                        "Медведев"});
#line 302
 testRunner.Then("существует роль \"Врач\" со списком пользователей", ((string)(null)), table38, "Тогда ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
#line 305
 testRunner.And("существует роль \"Медсестра\" со списком пользователей", ((string)(null)), table39, "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удаление пользователя")]
        public virtual void УдалениеПользователя()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удаление пользователя", ((string[])(null)));
#line 308
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
            table40.AddRow(new string[] {
                        "Врач"});
            table40.AddRow(new string[] {
                        "Медсестра"});
            table40.AddRow(new string[] {
                        "Админ"});
#line 309
 testRunner.Given("существуют роли", ((string)(null)), table40, "Пусть ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "роль"});
            table41.AddRow(new string[] {
                        "Медсестра"});
            table41.AddRow(new string[] {
                        "Админ"});
#line 314
 testRunner.When("создают нового пользователя \"Медведев\" с назначенными ролями", ((string)(null)), table41, "Когда ");
#line 318
 testRunner.And("удаляют пользователя \"Медведев\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 319
 testRunner.Then("существует 3 пользователя", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
#line 320
 testRunner.Then("существует роль \"Врач\" со списком пользователей", ((string)(null)), table42, "Тогда ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "имя"});
#line 322
 testRunner.And("существует роль \"Медсестра\" со списком пользователей", ((string)(null)), table43, "И ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
